#define	SMALL_EXPLO			0
#define	GUN_SHOT1			1
#define	GUN_SHOT2			2
#define	HULK_ALERT			3
#define	LEAPER_CHITTER		4	
#define	LEAPER_DEATH		5	
#define	SHOTGUN_READY		6	
#define	HULK_DEATH			7	
#define BIG_EXPLO			8	
#define	INF_WEAPON_FIRE		9	
#define	ALIEN_CHITTER		10	
#define	ALIEN_DEATH			11		
#define	ALIEN_GUN_READY		12	
#define	ARROW_FLYING		13	
#define	BULLET_IMPACT_METAL	14	
#define	BULLET_IMPACT_FLESH	15	
#define	BULLET_IMPACT_HARD	16		
#define	BOW_TWANG			17	
#define	LEAPER_DEATH		18
#define	HUMAN_FALL_KNEE		19
#define	HUMAN_DEATH1		20		
#define	HUMAN_DEATH2		21
#define	HUMAN_DEATH3		22		
#define	HUMAN_DEATH4		23	
#define	ITS_HIM				24	
#define	CMON				25	
#define	HEY					26	
#define	HUMAN_DEATH5		27	
#define	TOMAHAWK_SLASH		28	
#define	BULLET_RICOCHET		29	
#define READY_PISTOL		30
#define	MINI_GUN_ONE_SHOT	31
#define	MINI_GUN_MULTI_SHOT	32	
#define	DINO_GROWL			33	
#define	STAB_KNIFE			34
#define	SHOTGUN_BLAST		35	
#define	SERVO_LOOP			36
#define	RAPTOR_ALERT		37
		