#!smake -k
#
# Makefile for Spin demo application 
#
#
#

PRDEPTH = ../../../..

include $(PRDEPTH)/PRdefs

include $(COMMONRULES)

install:
		$(INSTALL) -m 444 -F /usr/src/PR/spin/ui/scripts Makefile *.rec



