#
# Makefile for tengine application
#
#

## FOR FINAL VERSION MAKE SURE

#CVERSION   = -O3 -mips2 -xansi

#LDFLAGS =	$(MKDEPOPT) -nostdlib -L$(ROOT)/usr/lib -lultra_rom

#rom $(APP):	spec $(OBJECTS) $(MAKEROM)
#		$(MAKEROM) -r rom spec
#		$(MAKEROM) -s 64 -f 0x00 -r rom spec

include $(ROOT)/usr/include/make/PRdefs

##################################################################
# ADD SOURCE FILES HERE!!!!!!!!


./overlay/font/0.h	:	dosvers/overlay/font/0.h
								dos2unix dosvers/overlay/font/0.h > overlay/font/0.h

./overlay/font/1.h	:	dosvers/overlay/font/1.h
								dos2unix dosvers/overlay/font/1.h > overlay/font/1.h

./overlay/font/2.h	:	dosvers/overlay/font/2.h
								dos2unix dosvers/overlay/font/2.h > overlay/font/2.h

./overlay/font/3.h	:	dosvers/overlay/font/3.h
								dos2unix dosvers/overlay/font/3.h > overlay/font/3.h

./overlay/font/4.h	:	dosvers/overlay/font/4.h
								dos2unix dosvers/overlay/font/4.h > overlay/font/4.h

./overlay/font/5.h	:	dosvers/overlay/font/5.h
								dos2unix dosvers/overlay/font/5.h > overlay/font/5.h

./overlay/font/6.h	:	dosvers/overlay/font/6.h
								dos2unix dosvers/overlay/font/6.h > overlay/font/6.h

./overlay/font/7.h	:	dosvers/overlay/font/7.h
								dos2unix dosvers/overlay/font/7.h > overlay/font/7.h

./overlay/font/8.h	:	dosvers/overlay/font/8.h
								dos2unix dosvers/overlay/font/8.h > overlay/font/8.h

./overlay/font/9.h	:	dosvers/overlay/font/9.h
								dos2unix dosvers/overlay/font/9.h > overlay/font/9.h
./overlay/font/neg.h	:	dosvers/overlay/font/neg.h
								dos2unix dosvers/overlay/font/neg.h > overlay/font/neg.h
./overlay/font/ramp.h	:	dosvers/overlay/font/ramp.h
								dos2unix dosvers/overlay/font/ramp.h > overlay/font/ramp.h

./overlay/font/0_4.h	:	dosvers/overlay/font/0_4.h
								dos2unix dosvers/overlay/font/0_4.h > overlay/font/0_4.h
./overlay/font/1_4.h	:	dosvers/overlay/font/1_4.h
								dos2unix dosvers/overlay/font/1_4.h > overlay/font/1_4.h
./overlay/font/2_4.h	:	dosvers/overlay/font/2_4.h
								dos2unix dosvers/overlay/font/2_4.h > overlay/font/2_4.h
./overlay/font/3_4.h	:	dosvers/overlay/font/3_4.h
								dos2unix dosvers/overlay/font/3_4.h > overlay/font/3_4.h
./overlay/font/4_4.h	:	dosvers/overlay/font/4_4.h
								dos2unix dosvers/overlay/font/4_4.h > overlay/font/4_4.h
./overlay/font/5_4.h	:	dosvers/overlay/font/5_4.h
								dos2unix dosvers/overlay/font/5_4.h > overlay/font/5_4.h
./overlay/font/6_4.h	:	dosvers/overlay/font/6_4.h
								dos2unix dosvers/overlay/font/6_4.h > overlay/font/6_4.h
./overlay/font/7_4.h	:	dosvers/overlay/font/7_4.h
								dos2unix dosvers/overlay/font/7_4.h > overlay/font/7_4.h
./overlay/font/8_4.h	:	dosvers/overlay/font/8_4.h
								dos2unix dosvers/overlay/font/8_4.h > overlay/font/8_4.h
./overlay/font/9_4.h	:	dosvers/overlay/font/9_4.h
								dos2unix dosvers/overlay/font/9_4.h > overlay/font/9_4.h


./overlay/font/a.h	:	dosvers/overlay/font/a.h
								dos2unix dosvers/overlay/font/a.h > overlay/font/a.h
./overlay/font/b.h	:	dosvers/overlay/font/b.h
								dos2unix dosvers/overlay/font/b.h > overlay/font/b.h
./overlay/font/c.h	:	dosvers/overlay/font/c.h
								dos2unix dosvers/overlay/font/c.h > overlay/font/c.h
./overlay/font/d.h	:	dosvers/overlay/font/d.h
								dos2unix dosvers/overlay/font/d.h > overlay/font/d.h
./overlay/font/e.h	:	dosvers/overlay/font/e.h
								dos2unix dosvers/overlay/font/e.h > overlay/font/e.h
./overlay/font/f.h	:	dosvers/overlay/font/f.h
								dos2unix dosvers/overlay/font/f.h > overlay/font/f.h
./overlay/font/g.h	:	dosvers/overlay/font/g.h
								dos2unix dosvers/overlay/font/g.h > overlay/font/g.h
./overlay/font/h.h	:	dosvers/overlay/font/h.h
								dos2unix dosvers/overlay/font/h.h > overlay/font/h.h
./overlay/font/i.h	:	dosvers/overlay/font/i.h
								dos2unix dosvers/overlay/font/i.h > overlay/font/i.h
./overlay/font/j.h	:	dosvers/overlay/font/j.h
								dos2unix dosvers/overlay/font/j.h > overlay/font/j.h
./overlay/font/k.h	:	dosvers/overlay/font/k.h
								dos2unix dosvers/overlay/font/k.h > overlay/font/k.h
./overlay/font/l.h	:	dosvers/overlay/font/l.h
								dos2unix dosvers/overlay/font/l.h > overlay/font/l.h
./overlay/font/m.h	:	dosvers/overlay/font/m.h
								dos2unix dosvers/overlay/font/m.h > overlay/font/m.h
./overlay/font/n.h	:	dosvers/overlay/font/n.h
								dos2unix dosvers/overlay/font/n.h > overlay/font/n.h
./overlay/font/o.h	:	dosvers/overlay/font/o.h
								dos2unix dosvers/overlay/font/o.h > overlay/font/o.h
./overlay/font/p.h	:	dosvers/overlay/font/p.h
								dos2unix dosvers/overlay/font/p.h > overlay/font/p.h
./overlay/font/q.h	:	dosvers/overlay/font/q.h
								dos2unix dosvers/overlay/font/q.h > overlay/font/q.h
./overlay/font/r.h	:	dosvers/overlay/font/r.h
								dos2unix dosvers/overlay/font/r.h > overlay/font/r.h
./overlay/font/s.h	:	dosvers/overlay/font/s.h
								dos2unix dosvers/overlay/font/s.h > overlay/font/s.h
./overlay/font/t.h	:	dosvers/overlay/font/t.h
								dos2unix dosvers/overlay/font/t.h > overlay/font/t.h
./overlay/font/u.h	:	dosvers/overlay/font/u.h
								dos2unix dosvers/overlay/font/u.h > overlay/font/u.h
./overlay/font/v.h	:	dosvers/overlay/font/v.h
								dos2unix dosvers/overlay/font/v.h > overlay/font/v.h
./overlay/font/w.h	:	dosvers/overlay/font/w.h
								dos2unix dosvers/overlay/font/w.h > overlay/font/w.h
./overlay/font/x.h	:	dosvers/overlay/font/x.h
								dos2unix dosvers/overlay/font/x.h > overlay/font/x.h
./overlay/font/y.h	:	dosvers/overlay/font/y.h
								dos2unix dosvers/overlay/font/y.h > overlay/font/y.h
./overlay/font/z.h	:	dosvers/overlay/font/z.h
								dos2unix dosvers/overlay/font/z.h > overlay/font/z.h
./overlay/font/copy.h	:	dosvers/overlay/font/copy.h
							dos2unix dosvers/overlay/font/copy.h > overlay/font/copy.h
./overlay/font/litl-c.h	:	dosvers/overlay/font/litl-c.h
							dos2unix dosvers/overlay/font/litl-c.h > overlay/font/litl-c.h
./overlay/font/period.h	:	dosvers/overlay/font/period.h
							dos2unix dosvers/overlay/font/period.h > overlay/font/period.h
./overlay/font/comma.h	:	dosvers/overlay/font/comma.h
							dos2unix dosvers/overlay/font/comma.h > overlay/font/comma.h
./overlay/font/quote-l.h	:	dosvers/overlay/font/quote-l.h
							dos2unix dosvers/overlay/font/quote-l.h > overlay/font/quote-l.h
./overlay/font/quote-r.h	:	dosvers/overlay/font/quote-r.h
							dos2unix dosvers/overlay/font/quote-r.h > overlay/font/quote-r.h
./overlay/font/trade.h	:	dosvers/overlay/font/trade.h
							dos2unix dosvers/overlay/font/trade.h > overlay/font/trade.h
./overlay/font/font.h	:	dosvers/overlay/font/font.h
							dos2unix dosvers/overlay/font/font.h > overlay/font/font.h


./overlay/pause/slab.h	:	dosvers/overlay/pause/slab.h
						 	dos2unix	dosvers/overlay/pause/slab.h > overlay/pause/slab.h
./overlay/pause/pause.h	:	dosvers/overlay/pause/pause.h
				  			dos2unix	dosvers/overlay/pause/pause.h > overlay/pause/pause.h
./overlay/pause/game.h	:	dosvers/overlay/pause/game.h
					 		dos2unix	dosvers/overlay/pause/game.h > overlay/pause/game.h
./overlay/pause/over.h	:	dosvers/overlay/pause/over.h
					 		dos2unix	dosvers/overlay/pause/over.h > overlay/pause/over.h
./overlay/pause/options.h	:	dosvers/overlay/pause/options.h
					 		dos2unix	dosvers/overlay/pause/options.h > overlay/pause/options.h

./overlay/invent/key2.h	:	dosvers/overlay/invent/key2.h
					 		dos2unix	dosvers/overlay/invent/key2.h > overlay/invent/key2.h
./overlay/invent/key3.h	:	dosvers/overlay/invent/key3.h
					 		dos2unix	dosvers/overlay/invent/key3.h > overlay/invent/key3.h
./overlay/invent/key4.h	:	dosvers/overlay/invent/key4.h
					 		dos2unix	dosvers/overlay/invent/key4.h > overlay/invent/key4.h
./overlay/invent/key5.h	:	dosvers/overlay/invent/key5.h
					 		dos2unix	dosvers/overlay/invent/key5.h > overlay/invent/key5.h
./overlay/invent/key6.h	:	dosvers/overlay/invent/key6.h
					 		dos2unix	dosvers/overlay/invent/key6.h > overlay/invent/key6.h
./overlay/invent/key7.h	:	dosvers/overlay/invent/key7.h
					 		dos2unix	dosvers/overlay/invent/key7.h > overlay/invent/key7.h
./overlay/invent/key8.h	:	dosvers/overlay/invent/key8.h
					 		dos2unix	dosvers/overlay/invent/key8.h > overlay/invent/key8.h
./overlay/invent/chrono.h	:	dosvers/overlay/invent/chrono.h
					 		dos2unix	dosvers/overlay/invent/chrono.h > overlay/invent/chrono.h



./overlay/pause/bar.h	:	dosvers/overlay/pause/bar.h
							dos2unix	dosvers/overlay/pause/bar.h > overlay/pause/bar.h
./overlay/pause/slider.h	:	dosvers/overlay/pause/slider.h
								dos2unix	dosvers/overlay/pause/slider.h > overlay/pause/slider.h



./overlay/health/health.h	:	dosvers/overlay/health/health.h
										dos2unix	dosvers/overlay/health/health.h > overlay/health/health.h
./overlay/health/walk.h		:	dosvers/overlay/health/walk.h
										dos2unix	dosvers/overlay/health/walk.h > overlay/health/walk.h
./overlay/health/run.h		:	dosvers/overlay/health/run.h
										dos2unix	dosvers/overlay/health/run.h > overlay/health/run.h
./overlay/health/armour.h	:	dosvers/overlay/health/armour.h
										dos2unix	dosvers/overlay/health/armour.h > overlay/health/armour.h
./overlay/health/turkhead.h	:	dosvers/overlay/health/turkhead.h
										dos2unix	dosvers/overlay/health/turkhead.h > overlay/health/turkhead.h
./overlay/health/airbar.h	:	dosvers/overlay/health/airbar.h
										dos2unix	dosvers/overlay/health/airbar.h > overlay/health/airbar.h
./overlay/health/bosbar.h	:	dosvers/overlay/health/bosbar.h
										dos2unix	dosvers/overlay/health/bosbar.h > overlay/health/bosbar.h
./overlay/health/lens.h		:	dosvers/overlay/health/lens.h
										dos2unix	dosvers/overlay/health/lens.h > overlay/health/lens.h
./overlay/health/sun.h		:	dosvers/overlay/health/sun.h
										dos2unix	dosvers/overlay/health/sun.h > overlay/health/sun.h
./overlay/health/liforce.h	:	dosvers/overlay/health/liforce.h
										dos2unix	dosvers/overlay/health/liforce.h > overlay/health/liforce.h
./overlay/compass/nesw.h	:	dosvers/overlay/compass/nesw.h
										dos2unix	dosvers/overlay/compass/nesw.h > overlay/compass/nesw.h
./overlay/health/bar.h		:	dosvers/overlay/health/bar.h
										dos2unix	dosvers/overlay/health/bar.h > overlay/health/bar.h
./overlay/health/bargrad.h 	:	dosvers/overlay/health/bargrad.h
										dos2unix	dosvers/overlay/health/bargrad.h > overlay/health/bargrad.h



./overlay/boxes/rok.h		:	dosvers/overlay/boxes/rok.h
										dos2unix dosvers/overlay/boxes/rok.h > overlay/boxes/rok.h


./overlay/ammo/arrow.h		:	dosvers/overlay/ammo/arrow.h
										dos2unix dosvers/overlay/ammo/arrow.h > overlay/ammo/arrow.h

./overlay/ammo/xarrow.h		:	dosvers/overlay/ammo/xarrow.h
										dos2unix dosvers/overlay/ammo/xarrow.h > overlay/ammo/xarrow.h

./overlay/ammo/bullet.h		:	dosvers/overlay/ammo/bullet.h
										dos2unix dosvers/overlay/ammo/bullet.h > overlay/ammo/bullet.h

./overlay/ammo/shell.h		:	dosvers/overlay/ammo/shell.h
										dos2unix dosvers/overlay/ammo/shell.h > overlay/ammo/shell.h

./overlay/ammo/xshell.h		:	dosvers/overlay/ammo/xshell.h
										dos2unix dosvers/overlay/ammo/xshell.h > overlay/ammo/xshell.h

./overlay/ammo/energy.h		:	dosvers/overlay/ammo/energy.h
										dos2unix dosvers/overlay/ammo/energy.h > overlay/ammo/energy.h

./overlay/ammo/minigun.h	:	dosvers/overlay/ammo/minigun.h
										dos2unix dosvers/overlay/ammo/minigun.h > overlay/ammo/minigun.h

./overlay/ammo/grenade.h	:	dosvers/overlay/ammo/grenade.h
										dos2unix dosvers/overlay/ammo/grenade.h > overlay/ammo/grenade.h

./overlay/ammo/rocket.h		:	dosvers/overlay/ammo/rocket.h
										dos2unix dosvers/overlay/ammo/rocket.h > overlay/ammo/rocket.h

./overlay/ammo/shockwav.h	:	dosvers/overlay/ammo/shockwav.h
										dos2unix dosvers/overlay/ammo/shockwav.h > overlay/ammo/shockwav.h

./overlay/ammo/kamf.h	   	:	dosvers/overlay/ammo/kamf.h
										dos2unix dosvers/overlay/ammo/kamf.h > overlay/ammo/kamf.h

./overlay/weapons/autosh.h	:	dosvers/overlay/weapons/autosh.h
										dos2unix	dosvers/overlay/weapons/autosh.h > overlay/weapons/autosh.h

./overlay/weapons/bow.h	:	dosvers/overlay/weapons/bow.h
									dos2unix	dosvers/overlay/weapons/bow.h > overlay/weapons/bow.h

./overlay/weapons/grenade.h	:	dosvers/overlay/weapons/grenade.h
											dos2unix	dosvers/overlay/weapons/grenade.h > overlay/weapons/grenade.h

./overlay/weapons/infntry.h	:	dosvers/overlay/weapons/infntry.h
											dos2unix	dosvers/overlay/weapons/infntry.h > overlay/weapons/infntry.h

./overlay/weapons/knife.h	:	dosvers/overlay/weapons/knife.h
										dos2unix	dosvers/overlay/weapons/knife.h > overlay/weapons/knife.h

./overlay/weapons/longhunt.h	:	dosvers/overlay/weapons/longhunt.h
											dos2unix	dosvers/overlay/weapons/longhunt.h > overlay/weapons/longhunt.h

./overlay/weapons/minigun.h	:	dosvers/overlay/weapons/minigun.h
											dos2unix	dosvers/overlay/weapons/minigun.h > overlay/weapons/minigun.h

./overlay/weapons/pistol.h	:	dosvers/overlay/weapons/pistol.h
										dos2unix	dosvers/overlay/weapons/pistol.h > overlay/weapons/pistol.h

./overlay/weapons/rifle.h	:	dosvers/overlay/weapons/rifle.h
										dos2unix	dosvers/overlay/weapons/rifle.h > overlay/weapons/rifle.h

./overlay/weapons/shotgun.h	:	dosvers/overlay/weapons/shotgun.h
											dos2unix	dosvers/overlay/weapons/shotgun.h > overlay/weapons/shotgun.h

./overlay/weapons/toma.h	:	dosvers/overlay/weapons/toma.h
										dos2unix	dosvers/overlay/weapons/toma.h > overlay/weapons/toma.h

./overlay/weapons/shock.h	:	dosvers/overlay/weapons/shock.h
										dos2unix	dosvers/overlay/weapons/shock.h > overlay/weapons/shock.h

./overlay/weapons/rocket.h	:	dosvers/overlay/weapons/rocket.h
										dos2unix	dosvers/overlay/weapons/rocket.h > overlay/weapons/rocket.h

./overlay/weapons/fusion.h	:	dosvers/overlay/weapons/fusion.h
									dos2unix	dosvers/overlay/weapons/fusion.h > overlay/weapons/fusion.h

./overlay/weapons/crone.h	:	dosvers/overlay/weapons/crone.h
									dos2unix	dosvers/overlay/weapons/crone.h > overlay/weapons/crone.h


./audio.h	:	dosvers/audio.h
					dos2unix dosvers/audio.h > audio.h

./audiocfx.h	:	dosvers/audiocfx.h
					dos2unix dosvers/audiocfx.h > audiocfx.h


./sfx.h	:	dosvers/sfx.h
				dos2unix dosvers/sfx.h > sfx.h

./onscrn.h	:	dosvers/onscrn.h
					dos2unix dosvers/onscrn.h > onscrn.h
./gfx16bit.h	:	dosvers/gfx16bit.h
					dos2unix dosvers/gfx16bit.h > gfx16bit.h


./hsb.h	:	dosvers/hsb.h
				dos2unix dosvers/hsb.h > hsb.h

./parttype.h	:	dosvers/parttype.h
						dos2unix dosvers/parttype.h > parttype.h

./shadowt.h	:	dosvers/shadowt.h
					dos2unix dosvers/shadowt.h > shadowt.h

./cartdir.h	:	dosvers/cartdir.h
					dos2unix dosvers/cartdir.h > cartdir.h

./matdefs.h	:	dosvers/matdefs.h
					dos2unix dosvers/matdefs.h > matdefs.h

./tengine.h	:	dosvers/tengine.h
					dos2unix dosvers/tengine.h > tengine.h

./map.h		:	dosvers/map.h
					dos2unix dosvers/map.h > map.h

./cppu64.h	:	dosvers/cppu64.h
					dos2unix dosvers/cppu64.h > cppu64.h

./spec.h		:	dosvers/spec.h
					dos2unix dosvers/spec.h > spec.h

./defs.h		:	dosvers/defs.h
					dos2unix dosvers/defs.h > defs.h

./memory.h	:	dosvers/memory.h
					dos2unix dosvers/memory.h > memory.h

./stdafx.h	:	dosvers/stdafx.h
					dos2unix dosvers/stdafx.h > stdafx.h

./debug.h	:	dosvers/debug.h
					dos2unix dosvers/debug.h > debug.h

./cart.h	:	dosvers/cart.h
				dos2unix dosvers/cart.h > cart.h

./hash.h	:	dosvers/hash.h
				dos2unix dosvers/hash.h > hash.h

./mattable.h	:	dosvers/mattable.h
						dos2unix dosvers/mattable.h > mattable.h

./scene.h	:	dosvers/scene.h
					dos2unix dosvers/scene.h > scene.h

./rommodel.h	:	dosvers/rommodel.h
						dos2unix dosvers/rommodel.h > rommodel.h

./anim.h		:	dosvers/anim.h
					dos2unix dosvers/anim.h > anim.h

./romstruc.h	:	dosvers/romstruc.h
						dos2unix dosvers/romstruc.h > romstruc.h

./graphu64.h	:	dosvers/graphu64.h
						dos2unix dosvers/graphu64.h > graphu64.h

./scaling.h	:	dosvers/scaling.h
					dos2unix dosvers/scaling.h > scaling.h

./control.h	:	dosvers/control.h
					dos2unix dosvers/control.h > control.h

./attract.h	:	dosvers/attract.h
					dos2unix dosvers/attract.h > attract.h

./tcontrol.h	:	dosvers/tcontrol.h
						dos2unix dosvers/tcontrol.h > tcontrol.h

./tmove.h	:	dosvers/tmove.h
					dos2unix dosvers/tmove.h > tmove.h

./geometry.h	:	dosvers/geometry.h
						dos2unix dosvers/geometry.h > geometry.h

./ai.h	:	dosvers/ai.h
				dos2unix dosvers/ai.h > ai.h

./aistand.h	:	dosvers/aistand.h
				dos2unix dosvers/aistand.h > aistand.h

./aiweap.h	:	dosvers/aiweap.h
					dos2unix dosvers/aiweap.h > aiweap.h

./particle.h	:	dosvers/particle.h
						dos2unix dosvers/particle.h > particle.h

./dlists.h	:	dosvers/dlists.h
					dos2unix dosvers/dlists.h > dlists.h

./volume.h	:	dosvers/volume.h
					dos2unix dosvers/volume.h > volume.h

./aistruc.h	:	dosvers/aistruc.h
					dos2unix dosvers/aistruc.h > aistruc.h

./frontend.h	:	dosvers/frontend.h
					dos2unix dosvers/frontend.h > frontend.h

./pause.h	:	dosvers/pause.h
		 			dos2unix dosvers/pause.h > pause.h

./train.h	:	dosvers/train.h
		 			dos2unix dosvers/train.h > train.h

./cheats.h	:	dosvers/cheats.h
		 			dos2unix dosvers/cheats.h > cheats.h


./pp.h		:	dosvers/pp.h
	 				dos2unix dosvers/pp.h > pp.h

./regtype.h	:	dosvers/regtype.h
					dos2unix dosvers/regtype.h > regtype.h


./boss.h	:	dosvers/boss.h
				dos2unix dosvers/boss.h > boss.h

./bossflgs.h	:	dosvers/bossflgs.h
						dos2unix dosvers/bossflgs.h > bossflgs.h

./fx.h	:	dosvers/fx.h
				dos2unix dosvers/fx.h > fx.h

./lists.h	:	dosvers/lists.h
				dos2unix dosvers/lists.h > lists.h

./hedtrack.h	:	dosvers/hedtrack.h
					dos2unix dosvers/hedtrack.h > hedtrack.h

./mantis.h	:	dosvers/mantis.h
					dos2unix dosvers/mantis.h > mantis.h

./trex.h	:	dosvers/trex.h
				dos2unix dosvers/trex.h > trex.h

./longhunt.h	:	dosvers/longhunt.h
				dos2unix dosvers/longhunt.h > longhunt.h

./humvee.h	:	dosvers/humvee.h
				dos2unix dosvers/humvee.h > humvee.h

./campaign.h	:	dosvers/campaign.h
				dos2unix dosvers/campaign.h > campaign.h



./textload.h	:	dosvers/textload.h
						dos2unix dosvers/textload.h > textload.h

./snddefs.h	:	dosvers/snddefs.h
					dos2unix dosvers/snddefs.h > snddefs.h

./aidoor.h	:	dosvers/aidoor.h
					dos2unix dosvers/aidoor.h > aidoor.h

./turret.h	:	dosvers/turret.h
					dos2unix dosvers/turret.h > turret.h

./pickup.h	:	dosvers/pickup.h
	  				dos2unix dosvers/pickup.h > pickup.h

./warp.h	:		dosvers/warp.h
	  				dos2unix dosvers/warp.h > warp.h

./options.h	:	dosvers/options.h
	  				dos2unix dosvers/options.h > options.h

./loadsave.h	:	dosvers/loadsave.h
	  				dos2unix dosvers/loadsave.h > loadsave.h

./simppool.h	:	dosvers/simppool.h
	  					dos2unix dosvers/simppool.h > simppool.h

./camera.h	:	dosvers/camera.h
	  				dos2unix dosvers/camera.h > camera.h

./cammodes.h	:	dosvers/cammodes.h
	  				dos2unix dosvers/cammodes.h > cammodes.h

./introcam.h	:	dosvers/introcam.h
	  				dos2unix dosvers/introcam.h > introcam.h

./cinecam.h	:	dosvers/cinecam.h
	  				dos2unix dosvers/cinecam.h > cinecam.h

./crdcam.h		:	dosvers/crdcam.h
	  					dos2unix dosvers/crdcam.h > crdcam.h

./galrecam.h	:	dosvers/galrecam.h
	  					dos2unix dosvers/galrecam.h > galrecam.h

./adpcm2.h	:	dosvers/adpcm2.h
	  				dos2unix dosvers/adpcm2.h > adpcm2.h

./version.h	:	dosvers/version.h
	  				dos2unix dosvers/version.h > version.h

./qsort.h	:	dosvers/qsort.h
	  				dos2unix dosvers/qsort.h > qsort.h

./wallcoll.h	:	dosvers/wallcoll.h
	  				dos2unix dosvers/wallcoll.h > wallcoll.h

./sun.h	:	dosvers/sun.h
	  			dos2unix dosvers/sun.h > sun.h

./unicol.h	:	dosvers/unicol.h
	  				dos2unix dosvers/unicol.h > unicol.h

./instcol.h	:	dosvers/instcol.h
	  				dos2unix dosvers/instcol.h > instcol.h

./wradcol.h	:	dosvers/wradcol.h
	  				dos2unix dosvers/wradcol.h > wradcol.h

./regicol.h	:	dosvers/regicol.h
	  				dos2unix dosvers/regicol.h > regicol.h

./collinfo.h	:	dosvers/collinfo.h
	  					dos2unix dosvers/collinfo.h > collinfo.h

./behavior.h	:	dosvers/behavior.h
						dos2unix dosvers/behavior.h > behavior.h


onscrn.c	:	dosvers/onscrn.cpp
				dos2unix dosvers/onscrn.cpp > onscrn.c
gfx16bit.c	:	dosvers/gfx16bit.cpp
				dos2unix dosvers/gfx16bit.cpp > gfx16bit.c

hsb.c	:	dosvers/hsb.cpp
			dos2unix dosvers/hsb.cpp > hsb.c

tengine.c	:	dosvers/tengine.cpp
					dos2unix dosvers/tengine.cpp > tengine.c

map.c		:	dosvers/map.cpp
					dos2unix dosvers/map.cpp > map.c

memory.c	:	dosvers/memory.cpp
				dos2unix dosvers/memory.cpp > memory.c

hash.c	:	dosvers/hash.cpp
				dos2unix dosvers/hash.cpp > hash.c

cart.c	:	dosvers/cart.cpp
				dos2unix dosvers/cart.cpp > cart.c

mattable.c	:	dosvers/mattable.cpp
			dos2unix dosvers/mattable.cpp > mattable.c

scene.c	:	dosvers/scene.cpp
				dos2unix dosvers/scene.cpp > scene.c

romstruc.c	:	dosvers/romstruc.cpp
					dos2unix dosvers/romstruc.cpp > romstruc.c

graphu64.c	:	dosvers/graphu64.cpp
					dos2unix dosvers/graphu64.cpp > graphu64.c

anim.c	:	dosvers/anim.cpp
				dos2unix dosvers/anim.cpp > anim.c

control.c	:	dosvers/control.cpp
					dos2unix dosvers/control.cpp > control.c

attract.c	:	dosvers/attract.cpp
					dos2unix dosvers/attract.cpp > attract.c

tcontrol.c	:	dosvers/tcontrol.cpp
					dos2unix dosvers/tcontrol.cpp > tcontrol.c

tmove.c		:	dosvers/tmove.cpp
					dos2unix dosvers/tmove.cpp > tmove.c

geometry.c	:	dosvers/geometry.cpp
					dos2unix dosvers/geometry.cpp > geometry.c

zbuffer.c	:	dosvers/zbuffer.cpp
					dos2unix dosvers/zbuffer.cpp > zbuffer.c

cfb.c		:	dosvers/cfb.cpp
				dos2unix dosvers/cfb.cpp > cfb.c

mempool.c	:	dosvers/mempool.cpp
					dos2unix dosvers/mempool.cpp > mempool.c

ai.c	:	dosvers/ai.cpp
			dos2unix dosvers/ai.cpp > ai.c

aistand.c	:	dosvers/aistand.cpp
					dos2unix dosvers/aistand.cpp > aistand.c

aiweap.c	:	dosvers/aiweap.cpp
				dos2unix dosvers/aiweap.cpp > aiweap.c

particle.c	:	dosvers/particle.cpp
					dos2unix dosvers/particle.cpp > particle.c

dlists.c	:	dosvers/dlists.cpp
				dos2unix dosvers/dlists.cpp > dlists.c

fifo.c	:	dosvers/fifo.cpp
				dos2unix dosvers/fifo.cpp > fifo.c

defs.c	:	dosvers/defs.cpp
				dos2unix dosvers/defs.cpp > defs.c

aistruc.c	:	dosvers/aistruc.cpp
					dos2unix dosvers/aistruc.cpp > aistruc.c

volume.c	:	dosvers/volume.cpp
				dos2unix dosvers/volume.cpp > volume.c

frontend.c	:	dosvers/frontend.cpp
					dos2unix dosvers/frontend.cpp > frontend.c

pause.c	:	dosvers/pause.cpp
	  			dos2unix dosvers/pause.cpp > pause.c

train.c		:	dosvers/train.cpp
	  			dos2unix dosvers/train.cpp > train.c

cheats.c	:	dosvers/cheats.cpp
	  			dos2unix dosvers/cheats.cpp > cheats.c


audio.c	:	dosvers/audio.cpp
	  			dos2unix dosvers/audio.cpp > audio.c

audiocfx.c	:	dosvers/audiocfx.cpp
		  			dos2unix dosvers/audiocfx.cpp > audiocfx.c

audiomgr.c	:	dosvers/audiomgr.cpp
	  				dos2unix dosvers/audiomgr.cpp > audiomgr.c

gfxyield.c	:	dosvers/gfxyield.cpp
	  				dos2unix dosvers/gfxyield.cpp > gfxyield.c

gdl.c		:	dosvers/gdl.cpp
	  			dos2unix dosvers/gdl.cpp > gdl.c

audheap.c	:	dosvers/audheap.cpp
	  				dos2unix dosvers/audheap.cpp > audheap.c

stacks.c	:	dosvers/stacks.cpp
	  			dos2unix dosvers/stacks.cpp > stacks.c

rnc1.s		:	dosvers/rnc1.s
	  				dos2unix dosvers/rnc1.s > rnc1.s

rnc2.s		:	dosvers/rnc2.s
	  				dos2unix dosvers/rnc2.s > rnc2.s

adpcm.s		:	dosvers/adpcm.s
	  				dos2unix dosvers/adpcm.s > adpcm.s

boss.c		:	dosvers/boss.cpp
					dos2unix dosvers/boss.cpp > boss.c

fx.c		:	dosvers/fx.cpp
					dos2unix dosvers/fx.cpp > fx.c

lists.c		:	dosvers/lists.cpp
					dos2unix dosvers/lists.cpp > lists.c

hedtrack.c		:	dosvers/hedtrack.cpp
					dos2unix dosvers/hedtrack.cpp > hedtrack.c

mantis.c	:	dosvers/mantis.cpp
	  			dos2unix dosvers/mantis.cpp > mantis.c

trex.c	:	dosvers/trex.cpp
	  			dos2unix dosvers/trex.cpp > trex.c

longhunt.c	:	dosvers/longhunt.cpp
	  			dos2unix dosvers/longhunt.cpp > longhunt.c

humvee.c	:	dosvers/humvee.cpp
	  			dos2unix dosvers/humvee.cpp > humvee.c

campaign.c	:	dosvers/campaign.cpp
	  			dos2unix dosvers/campaign.cpp > campaign.c



textload.c	:	dosvers/textload.cpp
	  				dos2unix dosvers/textload.cpp > textload.c

aidoor.c	:	dosvers/aidoor.cpp
	  			dos2unix dosvers/aidoor.cpp > aidoor.c

turret.c	:	dosvers/turret.cpp
	  			dos2unix dosvers/turret.cpp > turret.c

pickup.c	:	dosvers/pickup.cpp
	  			dos2unix dosvers/pickup.cpp > pickup.c

warp.c	:	dosvers/warp.cpp
	  			dos2unix dosvers/warp.cpp > warp.c

options.c	:	dosvers/options.cpp
	  			dos2unix dosvers/options.cpp > options.c

loadsave.c	:	dosvers/loadsave.cpp
	  			dos2unix dosvers/loadsave.cpp > loadsave.c

simppool.c	:	dosvers/simppool.cpp
	  				dos2unix dosvers/simppool.cpp > simppool.c

sched.c	:	dosvers/sched.cpp
	  			dos2unix dosvers/sched.cpp > sched.c

camera.c	:	dosvers/camera.cpp
	  	  		dos2unix dosvers/camera.cpp > camera.c

introcam.c	:	dosvers/introcam.cpp
	  				dos2unix dosvers/introcam.cpp > introcam.c

cinecam.c	:	dosvers/cinecam.cpp
	  				dos2unix dosvers/cinecam.cpp > cinecam.c

crdcam.c		:	dosvers/crdcam.cpp
	  				dos2unix dosvers/crdcam.cpp > crdcam.c

galrecam.c	:	dosvers/galrecam.cpp
	  				dos2unix dosvers/galrecam.cpp > galrecam.c

prfault.c	:	dosvers/prfault.cpp
	  	 			dos2unix dosvers/prfault.cpp > prfault.c

boot.c	:	dosvers/boot.cpp
	  	 		dos2unix dosvers/boot.cpp > boot.c

qsort.c	:	dosvers/qsort.cpp
	  	 		dos2unix dosvers/qsort.cpp > qsort.c

sun.c	:	dosvers/sun.cpp
	  	 	dos2unix dosvers/sun.cpp > sun.c

unicol.c	:	dosvers/unicol.cpp
	  	 		dos2unix dosvers/unicol.cpp > unicol.c

instcol.c	:	dosvers/instcol.cpp
	  	 			dos2unix dosvers/instcol.cpp > instcol.c

wradcol.c	:	dosvers/wradcol.cpp
	  	 			dos2unix dosvers/wradcol.cpp > wradcol.c

regicol.c	:	dosvers/regicol.cpp
	  	 			dos2unix dosvers/regicol.cpp > regicol.c

collinfo.c	:	dosvers/collinfo.cpp
	  	 			dos2unix dosvers/collinfo.cpp > collinfo.c

##################################################################

APP =		tengine

OPTIMIZER =

# must be -g2 for debugger to work
# -O2 is speed optimized
#CVERSION   = -g2 -mips2 -xansi
CVERSION   = -O2 -mips2 -xansi

TARGETS =	rom

HFILES =	./tengine.h ./map.h ./cppu64.h ./spec.h ./defs.h ./memory.h\
		./stdafx.h ./debug.h ./cart.h ./hash.h ./mattable.h\
		./scene.h ./rommodel.h ./anim.h ./romstruc.h\
		./graphu64.h ./scaling.h ./control.h ./attract.h ./geometry.h\
		./matdefs.h ./cartdir.h ./tcontrol.h ./tmove.h\
		./ai.h ./aistruc.h ./aistand.h ./aiweap.h ./particle.h ./dlists.h\
		./shadowt.h ./parttype.h ./hsb.h ./onscrn.h ./gfx16bit.h\
		./overlay/font/0.h ./overlay/font/1.h\
		./overlay/font/2.h ./overlay/font/3.h\
		./overlay/font/4.h ./overlay/font/5.h\
		./overlay/font/6.h ./overlay/font/7.h\
		./overlay/font/8.h ./overlay/font/9.h\
		./overlay/font/neg.h\
		./overlay/font/ramp.h\
		./overlay/font/0_4.h ./overlay/font/1_4.h\
		./overlay/font/2_4.h ./overlay/font/3_4.h\
		./overlay/font/4_4.h ./overlay/font/5_4.h\
		./overlay/font/6_4.h ./overlay/font/7_4.h\
		./overlay/font/8_4.h ./overlay/font/9_4.h\
		./overlay/font/a.h ./overlay/font/b.h\
		./overlay/font/c.h ./overlay/font/d.h\
		./overlay/font/e.h ./overlay/font/f.h\
		./overlay/font/g.h ./overlay/font/h.h\
		./overlay/font/i.h ./overlay/font/j.h\
		./overlay/font/k.h ./overlay/font/l.h\
		./overlay/font/m.h ./overlay/font/n.h\
		./overlay/font/o.h ./overlay/font/p.h\
		./overlay/font/q.h ./overlay/font/r.h\
		./overlay/font/s.h ./overlay/font/t.h\
		./overlay/font/u.h ./overlay/font/v.h\
		./overlay/font/w.h ./overlay/font/x.h\
		./overlay/font/y.h ./overlay/font/z.h\
		./overlay/font/copy.h ./overlay/font/litl-c.h\
		./overlay/font/period.h\
		./overlay/font/comma.h\
		./overlay/font/quote-l.h\
		./overlay/font/quote-r.h\
		./overlay/font/trade.h\
		./overlay/font/font.h\
		./overlay/pause/slab.h\
		./overlay/pause/pause.h\
		./overlay/pause/game.h\
		./overlay/pause/over.h\
		./overlay/pause/options.h\
		./overlay/pause/bar.h\
		./overlay/pause/slider.h\
		./overlay/invent/key2.h\
		./overlay/invent/key3.h\
		./overlay/invent/key4.h\
		./overlay/invent/key5.h\
		./overlay/invent/key6.h\
		./overlay/invent/key7.h\
		./overlay/invent/key8.h\
		./overlay/invent/chrono.h\
		./overlay/ammo/arrow.h\
		./overlay/ammo/xarrow.h\
		./overlay/ammo/bullet.h\
		./overlay/ammo/shell.h\
		./overlay/ammo/xshell.h\
		./overlay/ammo/energy.h\
		./overlay/ammo/minigun.h\
		./overlay/ammo/grenade.h\
		./overlay/ammo/rocket.h\
		./overlay/ammo/shockwav.h\
		./overlay/ammo/kamf.h\
		./overlay/boxes/rok.h\
		./overlay/health/health.h\
		./overlay/health/walk.h\
		./overlay/health/run.h\
		./overlay/health/armour.h\
		./overlay/health/turkhead.h\
		./overlay/health/liforce.h\
		./overlay/health/airbar.h\
		./overlay/health/bosbar.h\
		./overlay/health/lens.h\
		./overlay/health/sun.h\
		./overlay/health/bar.h\
		./overlay/health/bargrad.h\
		./overlay/compass/nesw.h\
		./overlay/weapons/autosh.h ./overlay/weapons/bow.h ./overlay/weapons/grenade.h ./overlay/weapons/infntry.h\
		./overlay/weapons/knife.h ./overlay/weapons/longhunt.h ./overlay/weapons/minigun.h ./overlay/weapons/pistol.h\
		./overlay/weapons/rifle.h ./overlay/weapons/shotgun.h ./overlay/weapons/toma.h\
		./overlay/weapons/shock.h ./overlay/weapons/rocket.h ./overlay/weapons/fusion.h\
		./overlay/weapons/crone.h\
 		./volume.h ./frontend.h ./pause.h ./train.h ./cheats.h\
		./audio.h ./audiocfx.h ./sfx.h ./pp.h ./regtype.h\
		./boss.h ./bossflgs.h ./fx.h ./lists.h ./hedtrack.h ./mantis.h ./trex.h ./longhunt.h ./humvee.h ./campaign.h\
		./textload.h ./snddefs.h ./aidoor.h ./turret.h ./pickup.h ./warp.h ./options.h ./loadsave.h ./simppool.h\
		./camera.h ./cammodes.h ./introcam.h ./cinecam.h ./crdcam.h ./galrecam.h ./adpcm2.h ./version.h ./qsort.h ./unicol.h ./sun.h
		./unicol.h ./instcol.h ./wradcol.h ./regicol.h ./collinfo.h ./behavior.h


CODEFILES   =	memory.c graphu64.c romstruc.c geometry.c textload.c\
		particle.c sched.c cart.c hash.c\
		tengine.c scene.c qsort.c mattable.c simppool.c anim.c\
		camera.c introcam.c cinecam.c crdcam.c galrecam.c\
		boss.c fx.c lists.c hedtrack.c mantis.c trex.c longhunt.c humvee.c campaign.c\
		control.c attract.c tcontrol.c tmove.c\
		ai.c aistand.c aiweap.c dlists.c hsb.c onscrn.c gfx16bit.c\
		defs.c aistruc.c volume.c frontend.c pause.c train.c cheats.c\
		audio.c audiocfx.c audiomgr.c gfxyield.c\
		aidoor.c turret.c pickup.c warp.c options.c loadsave.c prfault.c map.c sun.c adpcm.o\
		unicol.c instcol.c wradcol.c regicol.c collinfo.c

CODEOBJECTS = $(CODEFILES:.c=.o)

BOOTOBJECTS =	boot.o rnc1.o rnc2.o

DATAFILES   =	zbuffer.c cfb.c mempool.c fifo.c gdl.c audheap.c

DATAOBJECTS =	$(DATAFILES:.c=.o)

CODESEGMENT =	codesegment.o

BOOTSEGMENT =	bootsegment.o

STACKSEGMENT =	stacks.o

OBJECTS =	$(CODESEGMENT) $(DATAOBJECTS) $(BOOTSEGMENT) $(STACKSEGMENT)

LCDEFS =
LCINCS =	-I. -I$(ROOT)/usr/include/PR
LCOPTS =	-Xcpluscomm -fullwarn -wlint,-f -woff 513,813,819,822,827,831,835,826,852 -non_shared -float -G 0
#LCOPTS =	-fullwarn -woff 3255 -woff 3259 -woff 3577 -non_shared -G 0
#


#  -- debug library --
#LDFLAGS =	$(MKDEPOPT) -nostdlib -L$(ROOT)/usr/lib -lultra_d

#  -- non-debug library --
#LDFLAGS =	$(MKDEPOPT) -nostdlib -L$(ROOT)/usr/lib -lultra

#  -- rom library --
LDFLAGS =	$(MKDEPOPT) -nostdlib -L$(ROOT)/usr/lib -lultra_rom



### cpp fix
#CXXFLAGS := $(CXXFLAGS) $(LCOPTS)

LDIRT  =	$(APP) tengine

### cpp fix
#.SUFFIXES : .out .a .b .o .u .c .c++ .C .cxx .p .f .e .r .pl1 .pli \
#		.y .Y .yxx .l .L .lxx .s .sh .h .i \
#		.c,v .c++,v .f,v .p,v .pl1,v .pli,v .y,v .l,v .s,v .sh,v .h,v \
#		.Y,v .L,v .C,v .cxx,v .lxx,v .yxx,v .cpp

### cpp fix
#.cpp.out :
#	$(CXX) $(CXXFLAGS) $(.IMPSRC) $(LDFLAGS) -o $(.TARGET)
#.cpp.o :
#	$(CXX) $(CXXFLAGS) -c $(.IMPSRC)
#.cpp.s :
#	$(CXX) $(CXXFLAGS) -S $(.IMPSRC)
#.cpp.i :
#	$(CXX) $(CXXFLAGS) -E $(.IMPSRC) > $(.PREFIX).i


#$(CODEFILES)	:	dosvers/$(CODEFILES)
#			dos2unix dosvers/$(CODEFILES) > $(CODEFILES)


default:	$(HFILES) $(CODEFILES) $(TARGETS)

include $(COMMONRULES)

install:	default
		$(INSTALL) -m 444 -F /usr/src/PR/tengine \
			$(HFILES) $(CODEFILES) $(DATAFILES) Makefile spec README

rnc1.o : rnc1.s
	cc -c rnc1.s

rnc2.o : rnc2.s
	cc -c rnc2.s

adpcm.o : adpcm.s
	cc -c adpcm.s

$(CODESEGMENT):	$(CODEOBJECTS)
		$(LD) -o $(CODESEGMENT) -r $(CODEOBJECTS) $(LDFLAGS)

$(BOOTSEGMENT): $(BOOTOBJECTS)
		$(LD) -o $(BOOTSEGMENT) -r $(BOOTOBJECTS) $(MKDEPOPT) -nostdlib

rom $(APP):	spec $(OBJECTS) $(MAKEROM)
#		$(MAKEROM) -d -r rom spec
#		grep -h codeSegmentRom /tmp/*.s >segments
#		cat segments
#		rm /tmp/*.s
		$(MAKEROM) -r rom spec
#		$(MAKEROM) -s 128 -f 0x00 -r rom spec
#		$(MAKEROM) -s 96 -f 0x00 -r rom spec

#master :	spec $(OBJECTS) $(MAKEROM)
#		$(MAKEROM) -d -r rom spec
#		grep -h codeSegmentRom /tmp/*.s >segments
#		cat segments
#		rm /tmp/*.s
